---
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 The Linux Foundation

ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"
  autoupdate_commit_msg: "Chore: pre-commit autoupdate"

exclude: "^docs/conf.py"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
    language_version: python3
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ["--fix=lf"]
  - id: no-commit-to-branch
    args:
    - --branch=dev
    - --branch=master
    - --branch=main
    - --branch=rc
    - --branch=production
  - id: name-tests-test
    files: >-
      ^tests/[^_].*\.py$

- repo: https://github.com/jorisroovers/gitlint
  rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
  hooks:
  - id: gitlint

- repo: https://github.com/adrienverge/yamllint.git
  rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types:
    - file
    - yaml
    args:
    - --strict

- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/python-jsonschema/check-jsonschema.git
  rev: 0.29.2
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
  - id: check-jsonschema
    name: Check GitHub Workflows set timeout-minutes
    args:
    - --builtin-schema
    - github-workflows-require-timeout
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-readthedocs

- repo: https://github.com/PyCQA/pylint.git
  rev: v3.3.0
  hooks:
  - id: pylint
    args:
    - --disable
    - >-
      import-error,
      invalid-name,
      line-too-long,
      missing-class-docstring,
      missing-function-docstring,
      missing-module-docstring,
      protected-access,
      super-init-not-called,
      unused-argument,
      wrong-import-position,
    - --output-format
    - colorized

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: f0fe93c067104b76ffb58852abe79673a8429bd1  # frozen: v0.11.8
  hooks:
  - id: ruff
    files: ^(scripts|tests|custom_components)/.+\.py$
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
    files: ^(scripts|tests|custom_components)/.+\.py$

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: "f40886d54c729f533f864ed6ce584e920feb0af7" # frozen: v1.15.0
#   hooks:
#     - id: mypy
#       verbose: true
#       args: ["--show-error-codes", "--install-types", "--non-interactive"]
#       additional_dependencies:
#         - "pytest"
#         - "types-requests"
#         - "pypi_attestations"

# - repo: https://github.com/btford/write-good
#   rev: ab66ce10136dfad5146e69e70f82a3efac8842c1 # frozen: v1.0.8
#   hooks:
#     - id: write-good
#       files: "\\.(rst|md|markdown|mdown|mkdn)$"

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
  hooks:
  - id: shellcheck

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 586c3ea3f51230da42bab657c6a32e9e66c364f0  # frozen: v0.44.0
  hooks:
  - id: markdownlint
    args: ["--fix"]

- repo: https://github.com/fsfe/reuse-tool
  rev: 60dfc6b2ad9e1f3eabfbcf3a0dc202ee89dc5a00  # frozen: v5.0.2
  hooks:
  - id: reuse

# Replaces: https://github.com/rhysd/actionlint
# Permits actionlint to run both locally and with precommit.ci/GitHub
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: a185be0fd5b45112845b700d91b81050c75579e2  # frozen: v1.7.7.23
  hooks:
  - id: actionlint

# Check for misspellings in documentation files
- repo: https://github.com/codespell-project/codespell
  rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
  hooks:
  - id: codespell
    args: ["--ignore-words=.codespell"]
