---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: '📌 Audit GitHub Actions'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    - master
    paths: ['.github/**']

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  verify:
    name: 'Check SHA pinned actions'
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-verify-github-actions.yaml@fdcd10bc0fe174fe7d8834b2ba3a30159b4bf0bf  # v0.2.14
    permissions:
      contents: read
